version: "3.9"
services:
  blacksky-md:
    build: .
    container_name: blacksky-md
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./sessions:/app/sessions
      - ./database.json:/app/database.json
      - ./logs:/app/logs
      - ./tmp:/app/tmp
    environment:
      - SESSION_ID=BLACKSKY-MD
      - BOT_NAME=BLACKSKY-MD
      - OWNER_NUMBER=491556315347
      - PREFIX=.
      - NODE_ENV=production
    command: pm2-runtime ecosystem.config.js --env production
